FROM node:16-alpine

WORKDIR /app

# Copy package files
COPY package.json ./

# Install dependencies
RUN npm install --legacy-peer-deps

# Copy app code
COPY . .

# Expose port
EXPOSE 3000

# Start development server
CMD ["npm", "start"]
