ALTER TABLE videos ALTER COLUMN file_path DROP NOT NULL;
ALTER TABLE videos ADD COLUMN IF NOT EXISTS source_type VARCHAR(20) NOT NULL DEFAULT 'upload';
ALTER TABLE videos ADD COLUMN IF NOT EXISTS youtube_url TEXT;
